source 'https://rubygems.org'
gem 'sinatra'
gem 'rest-client'
gem 'nokogiri'
gem 'watir-webdriver'
gem 'headless'
gem 'json'
gem 'airbrake'
gem 'unicorn'
gem 'capistrano'
gem 'capistrano-unicorn', :require => false
