source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'rest-client'
gem 'nokogiri'
gem 'json'
gem 'airbrake'
gem 'unicorn'
gem 'capistrano'
gem 'capistrano-unicorn', :require => false
gem 'selenium-webdriver', '~> 2.35.1'
gem 'mechanize', '1.0.0'
gem 'rest-client'
gem 'awesome_print'
gem 'rspec'
gem 'rspec-mocks'
gem 'capybara'
gem 'activerecord', '~> 4.0.0.rc1'
gem 'sinatra-activerecord'
gem 'sqlite3'
gem 'iconv'
gem 'watir-webdriver'
gem 'headless'
