source 'https://rubygems.org'
gem 'sinatra'
gem 'rest-client'
gem 'nokogiri'
gem 'watir-webdriver'
gem 'headless'
gem 'json'
gem 'airbrake'
gem 'unicorn'
gem 'capistrano'
gem 'capistrano-unicorn', :require => false
gem 'selenium-webdriver', '~> 2.31.0'
gem 'mechanize'
gem 'rest-client'
gem 'awesome_print'
gem 'rspec'
gem 'capybara'
gem 'activerecord', '~> 4.0.0.rc1'
gem "sinatra-activerecord"
gem "sqlite3"
